const COPY={
ro:{calcNav:'Calculator',routeNav:'Rute',contactNav:'Contact',since:'COMPANIE DIN 2007',heroTitle:'Transport auto simplu și direct.',heroLead:'România ↔ Germania, Belgia, Olanda, Franța și Luxemburg. Vezi ruta, kilometrii și o estimare orientativă în câteva secunde.',estimateBtn:'Calculează prețul',realFleet:'Fotografii reale',direct:'Contact direct',estLabel:'ESTIMARE EDOMARC',calcTitle:'Calculează transportul',clientType:'Tip client',privateClient:'Persoană fizică',businessClient:'Persoană juridică',pickup:'Încărcare',delivery:'Descărcare',vehicle:'Vehicul',car:'Autoturism',suv:'SUV / crossover',big:'SUV mare / pickup',van:'Dubă / van',commercial:'Utilitară mare',nonrunning:'Nerulabil',calculate:'Calculează ruta și prețul',fact1:'Transport auto internațional',fact2:'Pentru persoane și companii',fact3:'Ofertă confirmată direct',mapEyebrow:'RUTA TA',mapTitle:'Hartă satelit, nu o schiță.',mapLead:'După calcul, traseul real apare aici. Dacă satelitul nu se încarcă stabil, harta trece automat pe modul rutier.',mapHint:'Completează calculatorul de sus pentru a afișa ruta.',proofEyebrow:'TRANSPORT REAL',proofTitle:'Fără imagini de stock în locul muncii noastre.',proofLead:'Pe site folosim fotografii din transporturile EDOMARC. Oferta finală ține cont de distanță, gabaritul vehiculului, locațiile exacte și disponibilitatea cursei.',confirmBtn:'Confirmă oferta pe WhatsApp',contactTitle:'Ai o mașină de transportat?',contactLead:'Trimite locațiile și modelul mașinii. Răspundem direct, fără formulare complicate.',sinceShort:'Din 2007',call:'Sună',loading:'Calculăm ruta…',error:'Nu am putut calcula automat ruta. Verifică localitățile sau deschide traseul în Google Maps.',roadDistance:'Distanță rutieră',estimate:'Estimare orientativă',final:'Preț orientativ. Oferta finală se confirmă după verificarea exactă a vehiculului, adreselor și disponibilității.',resolved:'Locații identificate',satFallback:'Satelitul nu s-a încărcat stabil. Am trecut automat pe harta rutieră.'},
de:{calcNav:'Rechner',routeNav:'Routen',contactNav:'Kontakt',since:'UNTERNEHMEN SEIT 2007',heroTitle:'Fahrzeugtransport. Einfach und direkt.',heroLead:'Rumänien ↔ Deutschland, Belgien, Niederlande, Frankreich und Luxemburg. Route, Kilometer und eine unverbindliche Schätzung in wenigen Sekunden.',estimateBtn:'Preis schätzen',realFleet:'Echte Fotos',direct:'Direkter Kontakt',estLabel:'EDOMARC SCHÄTZUNG',calcTitle:'Transport berechnen',clientType:'Kundentyp',privateClient:'Privatperson',businessClient:'Unternehmen',pickup:'Abholung',delivery:'Lieferung',vehicle:'Fahrzeug',car:'PKW',suv:'SUV / Crossover',big:'Großer SUV / Pickup',van:'Transporter / Van',commercial:'Großes Nutzfahrzeug',nonrunning:'Nicht fahrbereit',calculate:'Route und Preis berechnen',fact1:'Internationaler Fahrzeugtransport',fact2:'Privat- und Geschäftskunden',fact3:'Angebot direkt bestätigt',mapEyebrow:'IHRE ROUTE',mapTitle:'Satellitenkarte statt Skizze.',mapLead:'Nach der Berechnung erscheint die echte Route. Falls Satellitenbilder nicht stabil laden, wechselt die Karte automatisch zur Straßenansicht.',mapHint:'Rechner oben ausfüllen, um die Route anzuzeigen.',proofEyebrow:'ECHTE TRANSPORTE',proofTitle:'Echte Arbeit statt Stockfotos.',proofLead:'Wir verwenden Fotos aus echten EDOMARC-Transporten. Der Endpreis hängt von Entfernung, Fahrzeuggröße, genauen Adressen und Verfügbarkeit ab.',confirmBtn:'Angebot per WhatsApp bestätigen',contactTitle:'Fahrzeug zu transportieren?',contactLead:'Orte und Fahrzeugmodell senden. Wir antworten direkt, ohne komplizierte Formulare.',sinceShort:'Seit 2007',call:'Anrufen',loading:'Route wird berechnet…',error:'Die Route konnte nicht automatisch berechnet werden. Orte prüfen oder in Google Maps öffnen.',roadDistance:'Straßenentfernung',estimate:'Unverbindliche Schätzung',final:'Richtpreis. Das endgültige Angebot wird nach Prüfung von Fahrzeug, Adressen und Verfügbarkeit bestätigt.',resolved:'Erkannte Orte',satFallback:'Satellitenbilder wurden nicht stabil geladen. Die Karte wurde automatisch auf Straßenansicht umgestellt.'},
en:{calcNav:'Calculator',routeNav:'Routes',contactNav:'Contact',since:'COMPANY SINCE 2007',heroTitle:'Vehicle transport. Simple and direct.',heroLead:'Romania ↔ Germany, Belgium, Netherlands, France and Luxembourg. See the road route, distance and an indicative estimate in seconds.',estimateBtn:'Estimate price',realFleet:'Real photos',direct:'Direct contact',estLabel:'EDOMARC ESTIMATE',calcTitle:'Calculate transport',clientType:'Client type',privateClient:'Private',businessClient:'Company',pickup:'Pickup',delivery:'Delivery',vehicle:'Vehicle',car:'Car',suv:'SUV / crossover',big:'Large SUV / pickup',van:'Van',commercial:'Large commercial vehicle',nonrunning:'Non-running',calculate:'Calculate route and price',fact1:'International vehicle transport',fact2:'Private and business clients',fact3:'Quote confirmed directly',mapEyebrow:'YOUR ROUTE',mapTitle:'Satellite map, not a sketch.',mapLead:'After calculation, the real route appears here. If satellite imagery fails to load reliably, the map automatically switches to road view.',mapHint:'Use the calculator above to display the route.',proofEyebrow:'REAL TRANSPORTS',proofTitle:'Real work instead of stock photos.',proofLead:'We use photos from real EDOMARC transports. Final pricing depends on distance, vehicle dimensions, exact addresses and availability.',confirmBtn:'Confirm via WhatsApp',contactTitle:'Need to transport a vehicle?',contactLead:'Send the locations and vehicle model. We reply directly, without complicated forms.',sinceShort:'Since 2007',call:'Call',loading:'Calculating route…',error:'Could not calculate the route automatically. Check locations or open the route in Google Maps.',roadDistance:'Road distance',estimate:'Indicative estimate',final:'Indicative price. Final quote is confirmed after checking the exact vehicle, addresses and availability.',resolved:'Resolved locations',satFallback:'Satellite imagery did not load reliably. The map automatically switched to road view.'}}
let lang=localStorage.getItem('edomarc-lang')||'ro';
const phoneFor=()=>lang==='en'?{show:'0752 451 582',raw:'40752451582'}:{show:'0756 750 891',raw:'40756750891'};
function applyLang(l){lang=l;localStorage.setItem('edomarc-lang',l);document.documentElement.lang=l;document.querySelectorAll('[data-lang]').forEach(b=>b.classList.toggle('active',b.dataset.lang===l));document.querySelectorAll('[data-t]').forEach(el=>{let v=COPY[l][el.dataset.t];if(v)el.textContent=v});let p=phoneFor();document.querySelectorAll('[data-phone]').forEach(a=>{a.href='tel:+'+p.raw;if(!a.dataset.t)a.textContent=p.show});document.querySelectorAll('[data-wa]').forEach(a=>a.href='https://wa.me/'+p.raw)}
document.querySelectorAll('[data-lang]').forEach(b=>b.onclick=()=>applyLang(b.dataset.lang));applyLang(lang);document.getElementById('year').textContent=new Date().getFullYear();

let map,satellite,road,labels,line,markers=[],activeMapStyle='sat',satErrors=0,fallbackShown=false;
const mapShell=document.querySelector('.mapShell');
function mapNotice(text){if(!mapShell)return;let n=mapShell.querySelector('.mapNotice');if(!n){n=document.createElement('div');n.className='mapNotice';mapShell.appendChild(n)}n.textContent=text;clearTimeout(mapNotice.t);mapNotice.t=setTimeout(()=>n.remove(),5000)}
function setLayer(mode,auto=false){if(!map)return;activeMapStyle=mode;if(mode==='road'){if(map.hasLayer(satellite))map.removeLayer(satellite);if(map.hasLayer(labels))map.removeLayer(labels);if(!map.hasLayer(road))road.addTo(map);if(auto&&!fallbackShown){fallbackShown=true;mapNotice(COPY[lang].satFallback)}}else{if(map.hasLayer(road))map.removeLayer(road);if(!map.hasLayer(satellite))satellite.addTo(map);if(!map.hasLayer(labels))labels.addTo(map)}document.getElementById('satBtn').classList.toggle('active',mode==='sat');document.getElementById('roadBtn').classList.toggle('active',mode==='road');setTimeout(()=>map.invalidateSize(),60)}
if(typeof L!=='undefined'){
  map=L.map('map',{scrollWheelZoom:false,zoomControl:true,preferCanvas:true}).setView([49.1,11.2],5);
  satellite=L.tileLayer('https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}',{maxZoom:18,attribution:'Tiles © Esri',crossOrigin:true});
  labels=L.tileLayer('https://services.arcgisonline.com/ArcGIS/rest/services/Reference/World_Boundaries_and_Places/MapServer/tile/{z}/{y}/{x}',{maxZoom:18,crossOrigin:true});
  road=L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap contributors',crossOrigin:true});
  satellite.on('tileerror',()=>{satErrors++;if(activeMapStyle==='sat'&&satErrors>=5)setLayer('road',true)});labels.on('tileerror',()=>{satErrors++;if(activeMapStyle==='sat'&&satErrors>=7)setLayer('road',true)});satellite.on('tileload',()=>satErrors=Math.max(0,satErrors-1));
  satellite.addTo(map);labels.addTo(map);map.fitBounds(L.latLngBounds([[43.2,1],[54.5,30.5]]),{padding:[18,18]});setTimeout(()=>map.invalidateSize(),100);window.addEventListener('resize',()=>setTimeout(()=>map.invalidateSize(),100),{passive:true});
  document.getElementById('satBtn').onclick=()=>setLayer('sat');document.getElementById('roadBtn').onclick=()=>setLayer('road');
}else{mapNotice(COPY[lang].error)}

function normalizeQuery(q){let s=q.trim();[[/\bromânia\b/gi,'Romania'],[/\bromania\b/gi,'Romania'],[/\bgermania\b/gi,'Germany'],[/\bdeutschland\b/gi,'Germany'],[/\bolanda\b/gi,'Netherlands'],[/\bbelgia\b/gi,'Belgium'],[/\bfranța\b/gi,'France'],[/\bfranta\b/gi,'France'],[/\bluxemburg\b/gi,'Luxembourg']].forEach(([a,b])=>s=s.replace(a,b));return s}
async function fetchJSON(url,timeout=10000){const c=new AbortController(),t=setTimeout(()=>c.abort(),timeout);try{const r=await fetch(url,{headers:{Accept:'application/json'},signal:c.signal});if(!r.ok)throw new Error('http');return await r.json()}finally{clearTimeout(t)}}
async function geocodePhoton(q){let nq=normalizeQuery(q),j=await fetchJSON('https://photon.komoot.io/api/?limit=5&lang=en&q='+encodeURIComponent(nq));if(!j.features?.length)throw new Error('geo');let allowed=new Set(['Romania','Germany','Belgium','Netherlands','France','Luxembourg','Austria','Hungary','Czechia','Slovakia','Slovenia','Switzerland']);let f=j.features.find(x=>allowed.has(x.properties?.country))||j.features[0];let[lon,lat]=f.geometry.coordinates,p=f.properties||{},label=[p.name,p.city,p.state,p.country].filter((v,i,a)=>v&&a.indexOf(v)===i).join(', ')||q;return{lon,lat,label}}
async function geocodeNominatim(q){let nq=normalizeQuery(q),j=await fetchJSON('https://nominatim.openstreetmap.org/search?format=jsonv2&limit=3&addressdetails=1&countrycodes=ro,de,be,nl,fr,lu,at,hu,cz,sk,si,ch&q='+encodeURIComponent(nq),11000);if(!Array.isArray(j)||!j.length)throw new Error('geo2');return{lon:+j[0].lon,lat:+j[0].lat,label:j[0].display_name||q}}
async function geocode(q){try{return await geocodePhoton(q)}catch(e){return await geocodeNominatim(q)}}
async function getRoute(a,b){let tail=`${a.lon},${a.lat};${b.lon},${b.lat}?overview=full&geometries=geojson&steps=false`,urls=[`https://router.project-osrm.org/route/v1/driving/${tail}`,`https://routing.openstreetmap.de/routed-car/route/v1/driving/${tail}`],last;for(let u of urls){try{let j=await fetchJSON(u,14000);if(j.code==='Ok'&&j.routes?.length)return j.routes[0]}catch(e){last=e}}throw last||new Error('route')}
function round10(n){return Math.round(n/10)*10}
function price(km,type,nonrunning){let rate=Math.max(.42,Math.min(.76,.91-km*.00031));let factor={car:1,suv:1.12,big:1.20,van:1.38,commercial:1.48}[type]||1;let base=Math.max(330,km*rate)*factor+(nonrunning?80:0);return[round10(base*.95),round10(base*1.06)]}
function clearRoute(){if(line&&map)map.removeLayer(line);markers.forEach(m=>map&&map.removeLayer(m));line=null;markers=[]}
function draw(route,a,b){if(!map)return;clearRoute();let pts=route.geometry.coordinates.map(c=>[c[1],c[0]]);line=L.polyline(pts,{color:'#17bfe5',weight:5,opacity:.96}).addTo(map);let icon=letter=>L.divIcon({className:'edomarc-pin',html:`<div style="width:34px;height:34px;border-radius:50%;background:#071827;color:white;border:3px solid #6ce7ff;display:grid;place-items:center;font-weight:950;box-shadow:0 5px 18px rgba(0,0,0,.28)">${letter}</div>`,iconSize:[34,34],iconAnchor:[17,17]});markers=[L.marker([a.lat,a.lon],{icon:icon('A')}).addTo(map),L.marker([b.lat,b.lon],{icon:icon('B')}).addTo(map)];requestAnimationFrame(()=>{map.invalidateSize();map.fitBounds(line.getBounds(),{padding:[42,42],maxZoom:8})})}
function gmaps(a,b){return'https://www.google.com/maps/dir/?api=1&origin='+encodeURIComponent(a)+'&destination='+encodeURIComponent(b)+'&travelmode=driving'}
function clientName(t){return t==='business'?COPY[lang].businessClient:COPY[lang].privateClient}
function vehicleName(type){let all={ro:{car:'Autoturism',suv:'SUV / crossover',big:'SUV mare / pickup',van:'Dubă / van',commercial:'Utilitară mare'},de:{car:'PKW',suv:'SUV / Crossover',big:'Großer SUV / Pickup',van:'Transporter / Van',commercial:'Großes Nutzfahrzeug'},en:{car:'Car',suv:'SUV / crossover',big:'Large SUV / pickup',van:'Van',commercial:'Large commercial vehicle'}};return all[lang][type]||type}

document.getElementById('priceForm').onsubmit=async e=>{e.preventDefault();let f=new FormData(e.target),from=f.get('from').trim(),to=f.get('to').trim(),type=f.get('vehicle'),nr=f.get('nonrunning')==='on',client=f.get('clientType')||'private',res=document.getElementById('result'),sum=document.getElementById('routeSummary');res.className='result show';res.innerHTML='<b>'+COPY[lang].loading+'</b>';try{let[a,b]=await Promise.all([geocode(from),geocode(to)]),r=await getRoute(a,b),km=r.distance/1000,[lo,hi]=price(km,type,nr);draw(r,a,b);let p=phoneFor(),intro=lang==='ro'?'Salut EDOMARC! Doresc confirmarea unei estimări de transport.':lang==='de'?'Hallo EDOMARC! Ich möchte eine Transportschätzung bestätigen.':'Hello EDOMARC! I would like to confirm a transport estimate.',msg=`${intro}\n${COPY[lang].clientType}: ${clientName(client)}\n${from} → ${to}\n${vehicleName(type)}${nr?' · '+COPY[lang].nonrunning:''}\n${Math.round(km)} km\n${lo}–${hi} €`,wa='https://wa.me/'+p.raw+'?text='+encodeURIComponent(msg);res.innerHTML=`<div>${COPY[lang].roadDistance}: <b>${Math.round(km).toLocaleString()} km</b></div><div class="price">${lo}–${hi} €</div><div>${COPY[lang].final}</div><div class="resolved">${COPY[lang].resolved}: ${a.label} → ${b.label}</div><div class="resultActions"><a class="wa" target="_blank" href="${wa}">WhatsApp</a><a class="gm" target="_blank" href="${gmaps(from,to)}">Google Maps</a></div>`;sum.innerHTML=`<b>${from} → ${to}</b><br>${Math.round(km).toLocaleString()} km · ${lo}–${hi} €<div class="resolved">${a.label}<br>→ ${b.label}</div>`}catch(err){console.warn(err);res.innerHTML=`<b>${COPY[lang].error}</b><div class="resultActions"><a class="wa" target="_blank" href="https://wa.me/${phoneFor().raw}">WhatsApp</a><a class="gm" target="_blank" href="${gmaps(from,to)}">Google Maps</a></div>`}}